some more stuff

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -1,12 +1,12 @@
 BUILD_DIR := build
 
 CC := gcc
-CCFLAGS := -O2 -m32 -Wno-pointer-to-int-cast -I../include
+CCFLAGS := -Ofast -m32 -Wno-pointer-to-int-cast -I../include
 MAKE := make
 
 SOURCES=$(wildcard src/*.c)
 OBJECTS=$(patsubst src/%.c,$(BUILD_DIR)/%,$(SOURCES))
-
+OUTPUT=$(patsubst src/%.c,%,$(SOURCES))
 LIBRARY := ../linked.o
 
 default: mkdir build
@@ -18,7 +18,18 @@ $(BUILD_DIR)/%: src/%.c
 	$(CC) $(CCFLAGS) $^ -o $@ $(LIBRARY)
 
 build: $(OBJECTS)
-	echo here
+	cp $(OBJECTS) ./
+
+run_tests: $(OUTPUT)
+	@for TEST in $^; do \
+		echo -n "Testing $${TEST}: "; \
+		./$$TEST 2>/dev/null 1>/dev/null; \
+		if [ $$? -eq 0 ]; then \
+			echo "PASSED"; \
+		else \
+			echo "FAILED"; \
+		fi; \
+	done
 
 clean:
-	rm -rf ${BUILD_DIR}
+	rm -rf ${BUILD_DIR} ${OUTPUT}
